version: '3.8'

services:
  app:
    build: .
    ports:
      - "8085:8085"
    depends_on:
      - db
    env_file:
      - .env.docker

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: go_test_db
      POSTGRES_PASSWORD: go_test_db
      POSTGRES_DB: go_test_db
    ports:
      - "5432:5432"
